version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    env_file:
      - .env 
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - MONGODB_DATABASE=auth_service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: